version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/:rw
    environment:
      POSTGRES_DB: "base"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432